# Generated by Django 3.2.5 on 2022-04-08 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=255, verbose_name='案件名')),
                ('case_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='案件信息')),
                ('date_started', models.DateField(verbose_name='开始时间')),
                ('date_ended', models.DateField(verbose_name='结束时间')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='案件主管')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='服务名')),
                ('service_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='服务信息')),
                ('date_started', models.DateField(verbose_name='开始日期')),
                ('date_ended', models.DateField(verbose_name='结束日期')),
                ('provider_name', models.CharField(max_length=255, verbose_name='供应商名')),
                ('provider_contact_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='供应商联系方式')),
                ('case_belonged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='所属案件')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='服务负责人')),
            ],
        ),
    ]
