# Generated by Django 3.2.5 on 2022-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_ended',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_started',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_ended',
            field=models.DateTimeField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_started',
            field=models.DateTimeField(verbose_name='开始日期'),
        ),
    ]
