# Generated by Django 3.2.5 on 2022-04-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20220408_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='director',
        ),
    ]
