# Generated by Django 3.2.5 on 2022-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20220413_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
