# Generated by Django 3.2.5 on 2022-05-12 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20220415_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default='其他', max_length=20, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_started',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='date_ended',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_started',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='开始日期'),
            preserve_default=False,
        ),
    ]
