# Generated by Django 3.2.5 on 2022-05-12 12:46

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20220512_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.caseDocPath)),
                ('case_belonged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='所属案件')),
            ],
        ),
    ]
