# Generated by Django 3.2.5 on 2022-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casedoc_servdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(default='11', max_length=20, verbose_name='服务类型'),
        ),
    ]
