# Generated by Django 3.2.5 on 2022-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_service_type'),
    ]

    operations = [
    ]
