# Generated by Django 3.2.5 on 2022-05-15 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_servdoc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedoc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casedoc',
            name='type',
            field=models.CharField(default='1', max_length=3, verbose_name='文档类型'),
        ),
    ]
