# Generated by Django 3.2.5 on 2022-05-15 12:59

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20220515_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.servDocPath)),
                ('type', models.CharField(default='1', max_length=3, verbose_name='文档类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_belonged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='所属案件')),
                ('serv_belonged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.service', verbose_name='所属服务')),
            ],
        ),
    ]
