# Generated by Django 3.2.5 on 2022-05-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_servdoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servdoc',
            name='case_belonged',
        ),
    ]
