# Generated by Django 3.2.5 on 2022-05-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_remove_servdoc_case_belonged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_started',
            field=models.DateField(auto_now_add=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_started',
            field=models.DateField(auto_now_add=True, verbose_name='开始日期'),
        ),
    ]
